### ISSUE TITLE
Zookeeper service missing a port

### ISSUE THREAD

**Issue by phenry725** [Complexible/stardog-examples#32]
Need to expose 2181 through the zk-service service object.

The port is referenced when you bring up the cluster statefulset, [code here](https://github.com/stardog-union/stardog-examples/blob/develop/config/stardog-cluster.yaml#L87) without the port exposed the container will sit in the init state indefinitely.

**Comment by pdmars** [comment]
Thanks for the report. It does work without that exposed for some reason, however, you're correct that it should be the port that's exposed through the service. We'll update the example.
