### ISSUE TITLE
Could not initialize class vowpalWabbit.learner.VWLearners error

### ISSUE THREAD

**Issue by othadem** [Complexible/stardog-examples#59]
Hi Team,

  While Im running the machinelearning queries against movies.ttl database Im getting the below error. Can you please let me know the root cause and how to resolve this issue. 

000012: com.complexible.stardog.plan.eval.ExecutionException: Uncaught error during query evaluation: NoClassDefFoundError: Could not initialize class vowpalWabbit.learner.VWLearners

Query Im running is 2.simple_model.sparql from machinelearning folder

Thanks and Regards,
Omkar Thadem

**Comment by mhgrove** [comment]
@othadem, questions should be directed to community.stardog.com
